name = "PartialWaveFunctions"
uuid = "793d2195-304b-438e-bbb1-bc33c872ac39"
authors = ["Misha Mikhasenko"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
